CREATE TABLE ALUNOS
(
    MAT_ALU INTEGER NOT NULL ,
    NOM_ALU VARCHAR (50) NOT NULL ,
    TOT_CRED INTEGER NOT NULL ,
    DAT_NASC DATE NOT NULL ,
    MGP DECIMAL (5, 2) NOT NULL ,
    COD_CURSO INTEGER NOT NULL ,
)

;

CREATE TABLE CURSOS
(
    COD_CURSO INTEGER NOT NULL ,
    NOME_CURSO VARCHAR (40) NOT NULL ,
    TOT_CRED INTEGER NOT NULL ,
    IDT_PROF INTEGER
)